# Generated by Django 5.2.4 on 2025-07-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todomain', '0002_todo_is_completed_todo_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated_at']},
        ),
    ]
